### ISSUE TITLE
the same input produce different output

### ISSUE THREAD

**Issue by Eutenacity** [efeslab/fiddler#3]
I infer with the prompt "you". And the output is different if i run multi times

**Comment by tang-t21** [comment]
Ho do you run the model? I run it with "you" multi times, output is the same.

**Comment by Eutenacity** [comment]
python src/fiddler/infer.py --model "/VM/share/models/Mixtral-8x7V-v0.1/" --input you
first time:
<s> you
are
here
:
K
U
.
de
Fac
ult
ies
Fac
ulty
of
Human
ities
and
Social
Sciences
Department



second:
<s> you
are
here
:
K
U
.
de
Fac
ult
ies
and
Inst
itutes
Institute
for
Advanced
Study

**Comment by Eutenacity** [comment]
my transformer version is 4.37.1 so i add a weight input at /miniconda3/envs/dsmii/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py line 767-770 like :
    def forward(self, hidden_states,weight=1.0):
        current_hidden_states = self.act_fn(self.w1(hidden_states)) * self.w3(hidden_states)
        current_hidden_states = self.w2(current_hidden_states)
        return current_hidden_states*weight
but i do not think this matter

**Comment by Eutenacity** [comment]
I know the reason.  
"inps.to("cpu",non_blocking=True)" is bad
non_blocking will make the cpu matmul directly start the computaion without waiting "inps" to be copied to cpu. Of course, if the copy is very faster, this may not happen. But i think some kind of "wait" is needed.

**Comment by kamahori** [comment]
Hi @Eutenacity, thank you very much for figuring out the issue. That is actually a problem. I will fix it later.
